package reporter

import (
	"html/template"
	"io"

	"github.com/Siovos/siovos-audit/pkg/audit"
)

type HTMLReporter struct{}

func NewHTMLReporter() *HTMLReporter {
	return &HTMLReporter{}
}

func (r *HTMLReporter) Report(result *audit.AuditResult, w io.Writer) error {
	return htmlTmpl.Execute(w, result)
}

var htmlTmpl = template.Must(template.New("report").Funcs(template.FuncMap{
	"severityClass": func(s audit.Severity) string {
		switch s {
		case audit.SeverityPass:
			return "pass"
		case audit.SeverityInfo:
			return "info"
		case audit.SeverityWarn:
			return "warn"
		case audit.SeverityFail:
			return "fail"
		case audit.SeverityCritical:
			return "critical"
		default:
			return ""
		}
	},
	"scoreClass": func(score int) string {
		switch {
		case score >= 80:
			return "good"
		case score >= 60:
			return "moderate"
		default:
			return "bad"
		}
	},
	"groupByCheck": func(findings []audit.Finding) map[string][]audit.Finding {
		grouped := make(map[string][]audit.Finding)
		for _, f := range findings {
			grouped[f.CheckID] = append(grouped[f.CheckID], f)
		}
		return grouped
	},
}).Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Siovos Audit Report — {{ .Target }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }
  .container { max-width: 800px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .target { color: #94a3b8; margin-bottom: 2rem; }
  .overall { text-align: center; padding: 2rem; margin-bottom: 2rem; border-radius: 12px; background: #1e293b; }
  .overall .score { font-size: 4rem; font-weight: 700; }
  .overall .score.good { color: #4ade80; }
  .overall .score.moderate { color: #facc15; }
  .overall .score.bad { color: #f87171; }
  .category { background: #1e293b; border-radius: 8px; padding: 1.25rem; margin-bottom: 1rem; }
  .category-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem; }
  .category-name { font-weight: 600; font-size: 1.1rem; }
  .category-score { font-weight: 700; font-size: 1.1rem; }
  .category-score.good { color: #4ade80; }
  .category-score.moderate { color: #facc15; }
  .category-score.bad { color: #f87171; }
  .finding { display: flex; gap: 0.5rem; padding: 0.35rem 0; font-size: 0.9rem; }
  .tag { font-weight: 600; font-size: 0.8rem; border-radius: 4px; padding: 0.1rem 0.4rem; }
  .tag.pass { background: #166534; color: #4ade80; }
  .tag.info { background: #1e3a5f; color: #60a5fa; }
  .tag.warn { background: #713f12; color: #facc15; }
  .tag.fail { background: #7f1d1d; color: #f87171; }
  .tag.critical { background: #7f1d1d; color: #fca5a5; font-weight: 800; }
  .meta { color: #64748b; font-size: 0.8rem; margin-top: 2rem; text-align: center; }
</style>
</head>
<body>
<div class="container">
  <h1>Siovos Audit</h1>
  <p class="target">{{ .Target }}{{ if .Platform.Distro }} — {{ .Platform.Distro }}{{ end }}</p>

  <div class="overall">
    <div class="score {{ scoreClass .Score.Overall }}">{{ .Score.Overall }}/100</div>
    <div>Overall Score</div>
  </div>

  {{ $grouped := groupByCheck .Findings }}
  {{ range $cat, $score := .Score.Categories }}
  <div class="category">
    <div class="category-header">
      <span class="category-name">{{ $score.Name }}</span>
      <span class="category-score {{ scoreClass $score.Score }}">{{ $score.Score }}/100</span>
    </div>
    {{ range index $grouped $cat }}
    <div class="finding">
      <span class="tag {{ severityClass .Severity }}">{{ .Severity }}</span>
      <span>{{ .Title }}</span>
    </div>
    {{ end }}
  </div>
  {{ end }}

  <p class="meta">Generated by Siovos Audit at {{ .FinishedAt.Format "2006-01-02 15:04:05 UTC" }}</p>
</div>
</body>
</html>
`))
